apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-persistent-volume-claim-name
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
